name: Arduino Build

on:
  release:
    types: [published]
  pull_request:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: trackr-arduino
        path: ./Packages/cpp-arduino/